# Generated by Django 4.1.5 on 2023-01-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='category',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
