# Generated by Django 4.1.5 on 2023-01-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_warehouseitem_category_alter_warehouseitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseitem',
            old_name='category',
            new_name='value',
        ),
    ]
