# Generated by Django 4.1.5 on 2023-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_category_warehouseitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='value',
            field=models.IntegerField(),
        ),
    ]
